packages:
- packages/*
- apps/*
allowBuilds:
  '@parcel/watcher': false
  eccrypto: false
  esbuild: false
  mongodb-memory-server: false
  netlify-cli: false
  rxdb-premium: false
  secp256k1: false
  sharp: false
  unix-dgram: false
minimumReleaseAgeExclude:
- '@repo-toolkit/changelog@0.12.2'
- '@repo-toolkit/publish-package@0.12.2'
- '@repo-toolkit/publish-packages@0.12.2'
- '@repo-toolkit/release-artifact@0.12.2'
