packages:
- packages/*
- apps/*
allowBuilds:
  '@parcel/watcher': false
  eccrypto: false
  esbuild: false
  mongodb-memory-server: false
  netlify-cli: false
  rxdb-premium: false
  secp256k1: false
  sharp: false
  sqlite3: false
  unix-dgram: false
minimumReleaseAgeExclude:
- '@repo-toolkit/changelog@0.13.0 || 0.14.1 || 0.14.2 || 0.15.0 || 0.16.0'
- '@repo-toolkit/publish-package@0.13.0 || 0.14.1 || 0.14.2 || 0.15.0 || 0.16.0'
- '@repo-toolkit/publish-packages@0.13.0 || 0.14.1 || 0.14.2 || 0.15.0 || 0.16.0'
- '@repo-toolkit/release-artifact@0.13.0 || 0.14.1 || 0.14.2 || 0.15.0 || 0.16.0'
- '@egose/keycloak-fluent@0.12.0 || 0.12.1'
