packages:
- packages/*
- apps/*
patchedDependencies:
  '@repo-toolkit/publish-package@0.7.2': patches/@repo-toolkit__publish-package@0.7.2.patch
allowBuilds:
  '@parcel/watcher': false
  eccrypto: false
  esbuild: false
  mongodb-memory-server: false
  netlify-cli: false
  rxdb-premium: false
  secp256k1: false
  sharp: false
  unix-dgram: false
