name: Setup NPM Packages
description: Setup required NPM packages with caching for pnpm
runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/pnpm-packages@10cae796655b21f0f26d89546815206570bb9e2a
    with:
      frozen: 'true'
      ignore-scripts: 'true'
      paths: |
        .
        website
