import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve as pathResolve } from 'node:path';

/**
 * Version placeholder rewritten at publish time by `@repo-toolkit/publish-package`.
 */
export const CLI_VERSION = '0.0.0-PLACEHOLDER';

export function getCliVersion(): string {
  const candidateDirs = [
    typeof __dirname === 'string' ? __dirname : undefined,
    process.argv[1] ? dirname(pathResolve(process.argv[1])) : undefined,
    process.cwd(),
  ];
  const packageJsonPaths = candidateDirs.flatMap((dir) =>
    dir ? [pathResolve(dir, 'package.json'), pathResolve(dir, '..', 'package.json')] : [],
  );

  for (const packageJsonPath of packageJsonPaths) {
    if (!existsSync(packageJsonPath)) continue;

    try {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as { version?: unknown };
      if (typeof packageJson.version === 'string' && packageJson.version) {
        return packageJson.version;
      }
    } catch {
      // Fall through to the compile-time placeholder if package metadata is unreadable.
    }
  }

  return CLI_VERSION;
}

export type AccessRouterRuntimeSubcommand = 'dev' | 'build' | 'start' | 'build-serverless' | 'start-serverless';

function isSubcommand(value: string): value is AccessRouterRuntimeSubcommand {
  return (
    value === 'dev' ||
    value === 'build' ||
    value === 'start' ||
    value === 'build-serverless' ||
    value === 'start-serverless'
  );
}

export function printHelp(): void {
  console.log(`wtt-access-router-runtime

Generate config-driven access-router resource APIs on top of shared express-runtime CLI helpers.

Usage:
  wtt-access-router-runtime <command> <config-or-module> [options]
  wtt-access-router-runtime <config-file> [options]   (alias for dev)

Commands:
  dev                           Load an access-router-runtime config and run it locally
  build                         Bundle an access-router-runtime config as a local app module
  start                         Pass through to express-runtime start behavior
  build-serverless              Bundle an access-router-runtime config as a serverless handler
  start-serverless              Pass through to express-runtime start-serverless behavior

Config-aware commands:
  dev <config-file>             Supports TypeScript config files directly
  build <config-file>           Bundles the config-driven runtime as a local app module
  build-serverless <config-file>

Pass-through commands:
  start <app-module>            Same arguments as wtt-express-runtime start
  start-serverless <handler-module>

Examples:
  wtt-access-router-runtime ./src/access-router.config.ts --port 3000
  wtt-access-router-runtime ./src/access-router.config.ts --watch
  wtt-access-router-runtime ./src/access-router.config.ts --tsconfig ./tsconfig.json --watch
  wtt-access-router-runtime build ./src/access-router.config.ts --out-dir dist
  wtt-access-router-runtime build-serverless ./src/access-router.config.ts --out-dir netlify/functions
  wtt-access-router-runtime start ./dist/app.js --port 3000
  wtt-access-router-runtime start-serverless ./dist/handler.js --port 9000

Notes:
  - dev, build, and build-serverless expect a default config object, sync default factory, or named config object.
  - build and build-serverless manage runtime init automatically; do not pass --init yourself.
  - Remaining flags follow the same semantics as wtt-express-runtime.
  - --tsconfig is respected for config loading and build bundling on config-aware commands.
  - Watch supervision does not load the access-router-runtime config in the parent process.
  - Pass --watch <paths>, --ext, and --delay explicitly for watch supervision; bare --watch defaults to .
`);
}

export function normalizeAccessRouterRuntimeArgv(argv: string[]): string[] {
  const normalized = [...argv];
  const firstArg = normalized[0];
  const subcommand = isSubcommand(firstArg) ? firstArg : 'dev';
  if (subcommand !== 'dev') {
    return normalized;
  }

  const startIndex = isSubcommand(firstArg) ? 1 : 0;
  for (let index = startIndex; index < normalized.length; index += 1) {
    const arg = normalized[index];
    if (arg === '--') {
      break;
    }
    if (arg !== '--watch') {
      continue;
    }

    const nextArg = normalized[index + 1];
    if (nextArg === undefined || nextArg.startsWith('--')) {
      normalized[index] = '--watch=.';
    }
  }

  return normalized;
}

export function generateRuntimeEntryFromConfig(configPath: string, tsconfigPath?: string): string {
  const absoluteConfigPath = pathResolve(process.cwd(), configPath);
  void tsconfigPath;

  return [
    '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
    `import * as configModule from ${JSON.stringify(absoluteConfigPath)};`,
    `import { createAccessRouterRuntime, normalizeAccessRouterRuntimeConfigExport } from '@web-ts-toolkit/access-router-runtime';`,
    `const config = normalizeAccessRouterRuntimeConfigExport(configModule, ${JSON.stringify(configPath)});`,
    'const runtimeBundle = createAccessRouterRuntime(config);',
    'const app = runtimeBundle.app;',
    'export default app;',
    'export { app };',
    'export async function init() {',
    '  await runtimeBundle.init();',
    '}',
    'export async function shutdown() {',
    '  await runtimeBundle.shutdown();',
    '}',
    '',
  ].join('\n');
}

export function generateServerlessEntryFromConfig(configPath: string, tsconfigPath?: string): string {
  const absoluteConfigPath = pathResolve(process.cwd(), configPath);
  void tsconfigPath;

  return [
    '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
    `import * as configModule from ${JSON.stringify(absoluteConfigPath)};`,
    `import { createAccessRouterRuntimeServerlessHandler, normalizeAccessRouterRuntimeConfigExport } from '@web-ts-toolkit/access-router-runtime';`,
    `const config = normalizeAccessRouterRuntimeConfigExport(configModule, ${JSON.stringify(configPath)});`,
    'export const handler = createAccessRouterRuntimeServerlessHandler(config);',
    '',
  ].join('\n');
}
