import { createRequire } from 'node:module';
import { rmSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { resolve as pathResolve } from 'node:path';
import { spawn } from 'node:child_process';

/**
 * Version placeholder rewritten at publish time by `@repo-toolkit/publish-package`.
 */
export const CLI_VERSION = '0.0.0-PLACEHOLDER';

export type AccessRouterRuntimeSubcommand = 'dev' | 'build' | 'start' | 'build-serverless' | 'start-serverless';

export interface ResolvedCliInvocation {
  subcommand: AccessRouterRuntimeSubcommand;
  targetPath: string;
  passthroughArgs: string[];
  configAware: boolean;
}

const moduleRequire: NodeRequire = createRequire(pathResolve(process.cwd(), '.access-router-runtime-resolver.cjs'));

function isSubcommand(value: string): value is AccessRouterRuntimeSubcommand {
  return (
    value === 'dev' ||
    value === 'build' ||
    value === 'start' ||
    value === 'build-serverless' ||
    value === 'start-serverless'
  );
}

function isFlag(value: string): boolean {
  return value === '-h' || value === '--help' || value === '-V' || value === '--version';
}

function hasFlag(args: string[], name: string): boolean {
  return args.includes(name) || args.some((arg) => arg.startsWith(`${name}=`));
}

export function printHelp(): void {
  console.log(`wtt-access-router-runtime

Generate config-driven access-router resource APIs and hand execution off to wtt-express-runtime.

Usage:
  wtt-access-router-runtime <command> <config-or-module> [options]
  wtt-access-router-runtime <config-file> [options]   (alias for dev)

Commands:
  dev                           Load an access-router-runtime config and run it locally
  build                         Bundle an access-router-runtime config as a local app module
  start                         Pass through to wtt-express-runtime start
  build-serverless              Bundle an access-router-runtime config as a serverless handler
  start-serverless              Pass through to wtt-express-runtime start-serverless

Config-aware commands:
  dev <config-file>             Supports TypeScript config files directly
  build <config-file>           Generates a temporary app/init wrapper, then calls wtt-express-runtime build
  build-serverless <config-file>

Pass-through commands:
  start <app-module>            Same arguments as wtt-express-runtime start
  start-serverless <handler-module>

Examples:
  wtt-access-router-runtime ./src/access-router.config.ts --port 3000
  wtt-access-router-runtime build ./src/access-router.config.ts --out-dir dist
  wtt-access-router-runtime build-serverless ./src/access-router.config.ts --out-dir netlify/functions
  wtt-access-router-runtime start ./dist/app.js --port 3000
  wtt-access-router-runtime start-serverless ./dist/handler.js --port 9000

Notes:
  - dev, build, and build-serverless expect a config module whose default export is a config object.
  - build and build-serverless manage the init hook automatically; do not pass --init yourself.
  - Remaining flags are forwarded to wtt-express-runtime unchanged.
`);
}

export function resolveCliInvocation(argv: string[]): ResolvedCliInvocation | null {
  if (argv.length === 0 || argv.every(isFlag)) {
    return null;
  }

  const [firstArg, ...restArgs] = argv;
  const subcommand = isSubcommand(firstArg) ? firstArg : 'dev';
  const targetPath = isSubcommand(firstArg) ? restArgs[0] : firstArg;
  const passthroughArgs = isSubcommand(firstArg) ? restArgs.slice(1) : restArgs;

  if (!targetPath || isFlag(targetPath)) {
    throw new Error(
      `Missing required ${subcommand === 'start-serverless' ? 'handler module' : 'config or app module'} path.`,
    );
  }

  return {
    subcommand,
    targetPath,
    passthroughArgs,
    configAware: subcommand === 'dev' || subcommand === 'build' || subcommand === 'build-serverless',
  };
}

export interface GeneratedRuntimeFiles {
  appModulePath: string;
  initModulePath: string;
  cleanup: () => void;
}

export function createGeneratedRuntimeFiles(configPath: string): GeneratedRuntimeFiles {
  const id = randomUUID();
  const runtimeModulePath = pathResolve(process.cwd(), `.access-router-runtime-${id}.runtime.mjs`);
  const appModulePath = pathResolve(process.cwd(), `.access-router-runtime-${id}.app.mjs`);
  const initModulePath = pathResolve(process.cwd(), `.access-router-runtime-${id}.init.mjs`);
  const absoluteConfigPath = pathResolve(process.cwd(), configPath);

  writeFileSync(
    runtimeModulePath,
    [
      '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
      `import { createAccessRouterRuntime, loadAccessRouterRuntimeConfigSync } from '@web-ts-toolkit/access-router-runtime';`,
      `const config = loadAccessRouterRuntimeConfigSync(${JSON.stringify(absoluteConfigPath)});`,
      'export const runtimeBundle = createAccessRouterRuntime(config);',
      '',
    ].join('\n'),
    'utf8',
  );

  writeFileSync(
    appModulePath,
    [
      '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
      `import { runtimeBundle } from ${JSON.stringify(runtimeModulePath)};`,
      'let signalsRegistered = false;',
      'function registerSignals() {',
      '  if (signalsRegistered) return;',
      '  signalsRegistered = true;',
      '  const shutdown = () => { void runtimeBundle.shutdown(); };',
      "  process.once('SIGINT', shutdown);",
      "  process.once('SIGTERM', shutdown);",
      '}',
      'export default async function createApp() {',
      '  registerSignals();',
      '  await runtimeBundle.init();',
      '  return runtimeBundle.app;',
      '}',
      '',
    ].join('\n'),
    'utf8',
  );

  writeFileSync(
    initModulePath,
    [
      '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
      `import { runtimeBundle } from ${JSON.stringify(runtimeModulePath)};`,
      'export default function init() {',
      '  return runtimeBundle.init();',
      '}',
      '',
    ].join('\n'),
    'utf8',
  );

  return {
    appModulePath,
    initModulePath,
    cleanup() {
      rmSync(appModulePath, { force: true });
      rmSync(initModulePath, { force: true });
      rmSync(runtimeModulePath, { force: true });
    },
  };
}

export function buildDelegatedArgs(
  invocation: ResolvedCliInvocation,
  generated?: Pick<GeneratedRuntimeFiles, 'appModulePath' | 'initModulePath'>,
): string[] {
  if (!invocation.configAware) {
    return [invocation.subcommand, invocation.targetPath, ...invocation.passthroughArgs];
  }

  if (!generated) {
    throw new Error('Generated runtime files are required for config-aware commands.');
  }

  if (
    (invocation.subcommand === 'build' || invocation.subcommand === 'build-serverless') &&
    hasFlag(invocation.passthroughArgs, '--init')
  ) {
    throw new Error(`${invocation.subcommand} manages the init hook automatically. Remove --init.`);
  }

  if (invocation.subcommand === 'dev') {
    return ['dev', generated.appModulePath, ...invocation.passthroughArgs];
  }

  return [
    invocation.subcommand,
    generated.appModulePath,
    '--init',
    generated.initModulePath,
    ...invocation.passthroughArgs,
  ];
}

export function resolveExpressRuntimeCliPath(): string {
  return moduleRequire.resolve('@web-ts-toolkit/express-runtime/dist/cli.js');
}

export async function runDelegatedCommand(args: string[]): Promise<number> {
  const cliPath = resolveExpressRuntimeCliPath();

  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cliPath, ...args], {
      stdio: 'inherit',
    });

    child.once('error', reject);
    child.once('exit', (code, signal) => {
      if (signal) {
        resolve(1);
        return;
      }

      resolve(code ?? 0);
    });
  });
}
