import { resolve as pathResolve } from 'node:path';
import type { BuildArgs } from '@web-ts-toolkit/express-runtime/cli';

/**
 * Version placeholder rewritten at publish time by `@repo-toolkit/publish-package`.
 */
export const CLI_VERSION = '0.0.0-PLACEHOLDER';

export type AccessRouterRuntimeSubcommand = 'dev' | 'build' | 'start' | 'build-serverless' | 'start-serverless';

export interface ResolvedCliInvocation {
  subcommand: AccessRouterRuntimeSubcommand;
  targetPath: string;
  passthroughArgs: string[];
  configAware: boolean;
}

function isSubcommand(value: string): value is AccessRouterRuntimeSubcommand {
  return (
    value === 'dev' ||
    value === 'build' ||
    value === 'start' ||
    value === 'build-serverless' ||
    value === 'start-serverless'
  );
}

function isFlag(value: string): boolean {
  return value === '-h' || value === '--help' || value === '-V' || value === '--version';
}

export function printHelp(): void {
  console.log(`wtt-access-router-runtime

Generate config-driven access-router resource APIs on top of shared express-runtime CLI helpers.

Usage:
  wtt-access-router-runtime <command> <config-or-module> [options]
  wtt-access-router-runtime <config-file> [options]   (alias for dev)

Commands:
  dev                           Load an access-router-runtime config and run it locally
  build                         Bundle an access-router-runtime config as a local app module
  start                         Pass through to express-runtime start behavior
  build-serverless              Bundle an access-router-runtime config as a serverless handler
  start-serverless              Pass through to express-runtime start-serverless behavior

Config-aware commands:
  dev <config-file>             Supports TypeScript config files directly
  build <config-file>           Bundles the config-driven runtime as a local app module
  build-serverless <config-file>

Pass-through commands:
  start <app-module>            Same arguments as wtt-express-runtime start
  start-serverless <handler-module>

Examples:
  wtt-access-router-runtime ./src/access-router.config.ts --port 3000
  wtt-access-router-runtime build ./src/access-router.config.ts --out-dir dist
  wtt-access-router-runtime build-serverless ./src/access-router.config.ts --out-dir netlify/functions
  wtt-access-router-runtime start ./dist/app.js --port 3000
  wtt-access-router-runtime start-serverless ./dist/handler.js --port 9000

Notes:
  - dev, build, and build-serverless expect a config module whose default export is a config object.
  - build and build-serverless manage runtime init automatically; do not pass --init yourself.
  - Remaining flags follow the same semantics as wtt-express-runtime.
`);
}

export function resolveCliInvocation(argv: string[]): ResolvedCliInvocation | null {
  if (argv.length === 0 || argv.every(isFlag)) {
    return null;
  }

  const [firstArg, ...restArgs] = argv;
  const subcommand = isSubcommand(firstArg) ? firstArg : 'dev';
  const targetPath = isSubcommand(firstArg) ? restArgs[0] : firstArg;
  const passthroughArgs = isSubcommand(firstArg) ? restArgs.slice(1) : restArgs;

  if (!targetPath || isFlag(targetPath)) {
    throw new Error(
      `Missing required ${subcommand === 'start-serverless' ? 'handler module' : 'config or app module'} path.`,
    );
  }

  return {
    subcommand,
    targetPath,
    passthroughArgs,
    configAware: subcommand === 'dev' || subcommand === 'build' || subcommand === 'build-serverless',
  };
}

export function assertNoManualInit(subcommand: 'build' | 'build-serverless', args: BuildArgs): void {
  if (args.initPath) {
    throw new Error(`${subcommand} manages the init hook automatically. Remove --init.`);
  }
}

export function generateRuntimeEntryFromConfig(configPath: string): string {
  const absoluteConfigPath = pathResolve(process.cwd(), configPath);

  return [
    '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
    `import { createAccessRouterRuntime, loadAccessRouterRuntimeConfigSync } from '@web-ts-toolkit/access-router-runtime';`,
    `const config = loadAccessRouterRuntimeConfigSync(${JSON.stringify(absoluteConfigPath)});`,
    'const runtimeBundle = createAccessRouterRuntime(config);',
    'let signalsRegistered = false;',
    'function registerSignals() {',
    '  if (signalsRegistered) return;',
    '  signalsRegistered = true;',
    '  const shutdown = () => { void runtimeBundle.shutdown(); };',
    "  process.once('SIGINT', shutdown);",
    "  process.once('SIGTERM', shutdown);",
    '}',
    'registerSignals();',
    'const app = runtimeBundle.app;',
    'export default app;',
    'export { app };',
    'export async function init() {',
    '  await runtimeBundle.init();',
    '}',
    '',
  ].join('\n');
}

export function generateServerlessEntryFromConfig(configPath: string): string {
  const absoluteConfigPath = pathResolve(process.cwd(), configPath);

  return [
    '// Auto-generated by @web-ts-toolkit/access-router-runtime CLI - do not edit.',
    `import { createAccessRouterRuntimeServerlessHandler, loadAccessRouterRuntimeConfigSync } from '@web-ts-toolkit/access-router-runtime';`,
    `const config = loadAccessRouterRuntimeConfigSync(${JSON.stringify(absoluteConfigPath)});`,
    'export const handler = createAccessRouterRuntimeServerlessHandler(config);',
    '',
  ].join('\n');
}
