name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@6e49f5129448cff1d901b16032c09445bd49dde1

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
