name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@66a82313a99a4e502830eb48acc073aedcdbdce1

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
