name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@07bfea5b03e310822963a15dccc885c2d3385284

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
