import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  packagesSidebar: [{ type: 'autogenerated', dirName: 'packages' }],
};

export default sidebars;
