name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Run pre-commit
      uses: egose/actions/precommit@f77b6cc49f20cbc4c2a592f9dbda9a56ff796636
      with:
        config: .pre-commit-config.yaml
        commit-on-push: false
        commit-on-pr: false
