name: Check code/commit conventions

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Run pre-commit
      uses: egose/actions/precommit@ef042a54d9446c85fdd1044d342c614b5353f812
      with:
        config: .pre-commit-config.yaml
        commit-on-push: false
        commit-on-pr: false
