name: Publish NPM Packages

on:
  push:
    tags:
    - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - uses: hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Publish Packages
      run: |
        cat >"/home/runner/.npmrc" <<EOF
        //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        registry=https://registry.npmjs.org/
        always-auth=true
        EOF
        pnpm publish-all -- --tag ${{github.ref_name}}

    - name: Release
      uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
