name: Publish NPM Packages

on:
  push:
    tags:
    - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-npm

    - name: Publish Packages
      run: |
        cat >"/home/runner/.npmrc" <<EOF
        //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        registry=https://registry.npmjs.org/
        always-auth=true
        EOF
        pnpm publish-packages -- --version ${{github.ref_name}}
